apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rechpa/python-app.git
    targetRevision: HEAD
    path: argocd-app/
  destination:
    server: https://kubernetes.default.svc
    namespace: python
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
