---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
  namespace: cicd
spec:
  params:
    - name: git-url
      type: string
      description: Git repository URL
    - name: git-revision
      type: string
      description: Git revision to checkout (branch, tag, or commit)
      default: main
    - name: image-name
      type: string
      description: Name of the container image to build
    - name: image-tag
      type: string
      description: Tag for the container image
    - name: helm-chart-path
      type: string
      description: Path to Helm chart in the repository
      default: ./helm
    - name: deployment-namespace
      type: string
      description: Kubernetes namespace for deployment
      default: default
    - name: environment
      type: string
      description: Target environment (dev, staging, prod)
      default: dev
  
  workspaces:
    - name: shared-workspace
    - name: git-credentials
    - name: docker-credentials
  
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: basic-auth
          workspace: git-credentials
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"
    
    - name: build-image
      taskRef:
        name: kaniko
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: $(params.image-name):$(params.image-tag)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
    
    - name: update-helm-values
      taskRef:
        name: yq
      runAfter:
        - build-image
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: SCRIPT
          value: |
            yq eval '.image.tag = "$(params.image-tag)"' -i $(params.helm-chart-path)/values.yaml
            cat $(params.helm-chart-path)/values.yaml
    
    - name: helm-deploy
      taskRef:
        name: helm-upgrade
      runAfter:
        - update-helm-values
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: chart_path
          value: $(params.helm-chart-path)
        - name: release_name
          value: $(params.environment)-release
        - name: release_namespace
          value: $(params.deployment-namespace)
        - name: overwrite_values
          value: image.tag=$(params.image-tag)
    
    - name: verify-deployment
      taskRef:
        name: kubernetes-actions
      runAfter:
        - helm-deploy
      params:
        - name: script
          value: |
            kubectl rollout status deployment/$(params.environment)-release -n $(params.deployment-namespace) --timeout=5m
            kubectl get pods -n $(params.deployment-namespace) -l app=$(params.environment)-release

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: cicd
spec:
  description: Clone a git repository
  workspaces:
    - name: output
      description: The git repo will be cloned here
    - name: basic-auth
      description: Git credentials
      optional: true
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: main
    - name: deleteExisting
      type: string
      default: "true"
  steps:
    - name: clone
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
      script: |
        #!/bin/sh
        set -ex
        
        if [ "$(params.deleteExisting)" = "true" ]; then
          rm -rf $(workspaces.output.path)/*
        fi
        
        /ko-app/git-init \
          -url=$(params.url) \
          -revision=$(params.revision) \
          -path=$(workspaces.output.path)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko
  namespace: cicd
spec:
  description: Build and push container image using Kaniko
  workspaces:
    - name: source
    - name: dockerconfig
      description: Docker config for authentication
  params:
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      type: string
      default: ./Dockerfile
    - name: CONTEXT
      type: string
      default: .
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.11.0
      env:
        - name: DOCKER_CONFIG
          value: $(workspaces.dockerconfig.path)
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE)
        - --cache=true

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yq
  namespace: cicd
spec:
  description: Execute yq commands
  workspaces:
    - name: source
  params:
    - name: SCRIPT
      type: string
  steps:
    - name: yq
      image: mikefarah/yq:4
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -ex
        $(params.SCRIPT)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-upgrade
  namespace: cicd
spec:
  description: Deploy application using Helm
  workspaces:
    - name: source
  params:
    - name: chart_path
      type: string
    - name: release_name
      type: string
    - name: release_namespace
      type: string
    - name: overwrite_values
      type: string
      default: ""
  steps:
    - name: helm-upgrade
      image: alpine/helm:3.12.0
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -ex
        
        helm upgrade --install $(params.release_name) $(params.chart_path) \
          --namespace $(params.release_namespace) \
          --create-namespace \
          --set $(params.overwrite_values) \
          --wait \
          --timeout 5m

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubernetes-actions
  namespace: cicd
spec:
  description: Execute kubectl commands
  params:
    - name: script
      type: string
  steps:
    - name: kubectl
      image: bitnami/kubectl:1.27
      script: |
        #!/bin/bash
        set -ex
        $(params.script)